// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace COCOAPI
{

    internal partial class COCODataSet
    {
        internal abstract class Annotation
        {
            [JsonProperty("area")]
            public double Area { get; set; }

            [JsonProperty("iscrowd")]
            public int Iscrowd { get; set; }

            [JsonProperty("image_id")]
            public long ImageId { get; set; }

            [JsonProperty("bbox")]
            public double[] Bbox { get; set; }

            [JsonProperty("category_id")]
            public int CategoryId { get; set; }

            [JsonProperty("id")]
            public long Id { get; set; }
        }

        internal class Annotation1 : Annotation
        {
            [JsonProperty("segmentation")]
            public double[][] Segmentation1 { get; set; }
        }

        internal class Annotation2: Annotation
        {
            [JsonProperty("segmentation")]
            public Segmentation2 Segmentation2 { get; set; }
        }
    }

}
