// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace COCOAPI
{

    internal partial class COCODataSet
    {
        internal class Image
        {
            [JsonProperty("license")]
            public int License { get; set; }

            [JsonProperty("file_name")]
            public string FileName { get; set; }

            [JsonProperty("coco_url")]
            public string CocoUrl { get; set; }

            [JsonProperty("height")]
            public int Height { get; set; }

            [JsonProperty("width")]
            public int Width { get; set; }

            [JsonProperty("date_captured")]
            public string DateCaptured { get; set; }

            [JsonProperty("flickr_url")]
            public string FlickrUrl { get; set; }

            [JsonProperty("id")]
            public long Id { get; set; }
        }
    }

}
