// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace COCOAPI
{

    internal partial class COCODataSet
    {
        internal class Segmentation2
        {
            [JsonProperty("counts", Required = Required.AllowNull)]
            public int[] Counts { get; set; }

            [JsonProperty("size", Required = Required.AllowNull)]
            public int[] Size { get; set; }
        }
    }

}
